### ISSUE TITLE
Node update problem

### ISSUE THREAD

**Issue by dfizzo** [oznu/homebridge-config-ui-x#1640] opened 2023-11-07 00:59 UTC
### Current Situation

Hi - I updated node.js with sudo hb-service update-node, and now I cannot access homebridge UI. I am not an expert here so any guidance would be extremely appreciated!! Thank you everyone!!

### Logs

```markdown
Don’t have.
```

### Configuration

```json
Don’t have.
```

### Environment

- OS: raspbian
- Software: ?
- Node: ?
- npm: ?

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment] 2023-11-07 01:09
Duplicate of https://github.com/homebridge/homebridge/issues/3453

**Comment by bwp91** [comment] 2023-11-17 19:28
Closing as looks like it's a duplicate. Please feel free to reopen if you don't agree!

**Closed as completed by bwp91** 2023-11-17 19:28 UTC
Labels: question
