### ISSUE TITLE
[homebridge-config-ui-x] SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by marcoschmidt79** [oznu/homebridge-config-ui-x#299] opened 2019-05-17 17:44 UTC
I have installed config-ui-x 4.4.1 and node 12.2.0. after upgrading to 4.4.1 i get in 3 out of 8 instances when calling the web interface the following error message in the log

Mai 17 19:38:59 homebridge homebridge[25119]: [2019-5-17 19:38:59] [homebridge-config-ui-x] SyntaxError: Unexpected token %
Mai 17 19:38:59 homebridge homebridge[25119]: [2019-5-17 19:38:59] [homebridge-config-ui-x] SyntaxError: Unexpected token %
Mai 17 19:39:00 homebridge homebridge[25119]: [2019-5-17 19:39:00] [homebridge-config-ui-x] SyntaxError: Unexpected token %
Mai 17 19:39:01 homebridge homebridge[25119]: [2019-5-17 19:39:01] [homebridge-config-ui-x] SyntaxError: Unexpected token %

**Comment by cmdshft** [comment] 2019-05-18 00:49
Had this same issue after upgrading a plugin via the webui. I had to edit my json.config and remove the plugin via NPM to restore functionality.

**Comment by oznu** [comment] 2019-05-19 06:13
I think I know where this is is coming from, 4.4.2 should add a bit more detail to these messages to help figure it out.

**Comment by marcoschmidt79** [comment] 2019-05-19 14:56
Ok, i updated an: 

Mai 19 16:53:55 homebridge homebridge[21414]: [2019-5-19 16:53:55] [Broadlink] Klimaanlage Paul addTemperatureCallbackToQueue (requested temperature from device, waiting)
Mai 19 16:53:56 homebridge homebridge[21414]: [2019-5-19 16:53:56] [Broadlink] Klimaanlage Schlafzimmer onTemperature (20.6)
Mai 19 16:53:56 homebridge homebridge[21414]: [2019-5-19 16:53:56] [Broadlink] Klimaanlage Esszimmer onTemperature (22)
Mai 19 16:53:56 homebridge homebridge[21414]: [2019-5-19 16:53:56] [Broadlink] Klimaanlage Emil onTemperature (22.9)
Mai 19 16:53:56 homebridge homebridge[21414]: [2019-5-19 16:53:56] [Broadlink] Klimaanlage Paul onTemperature (22.7)
Mai 19 16:54:01 homebridge homebridge[21414]: [2019-5-19 16:54:01] [Config] Console v4.4.2 is listening on :: port 8030
Mai 19 16:54:05 homebridge homebridge[21414]: [2019-5-19 16:54:05] [Config] Multiple Instances Of Homebridge Found Installed
Mai 19 16:54:05 homebridge homebridge[21414]: [2019-5-19 16:54:05] [Config] /usr/local/lib/node_modules/homebridge
Mai 19 16:54:05 homebridge homebridge[21414]: [2019-5-19 16:54:05] [Config] /usr/lib/node_modules/homebridge
Mai 19 16:55:03 homebridge homebridge[21414]: [2019-5-19 16:55:03] [homebridge-config-ui-x] SyntaxError: Unexpected token %

**Comment by oznu** [comment] 2019-05-20 01:20
No change. Are you able to trigger this log from any particular action in the UI?

**Comment by marcoschmidt79** [comment] 2019-05-20 05:17
Sorry for my bad english.

I restart instance 1, go to UI from instance 1 and everything ok. I restart instance 2, i open the UI from instance 2 and ok. i open the UI from instance 1 and the screen from browser is white and the log from instance 1 say: SyntaxError: Unexpected token %

**Comment by Shana611** [comment] 2019-05-20 13:26
I have the same problem after updating to the new version

**Comment by justinfanok** [comment] 2019-05-22 16:21
Same issue: here's some log output from my setup
`[5/22/2019, 10:29:38 AM] Homebridge is running on port XXXX.
[0;37m[5/22/2019, 10:29:39 AM] [0m[0;36m[Config][0m [0;33mConsole v4.4.2 is listening on 0.0.0.0 port XXXXX[0m
[5/22/2019, 11:00:44 AM] [36m[homebridge-config-ui-x][0m [31mSyntaxError: Unexpected token %[0m
[5/22/2019, 11:00:44 AM] [36m[homebridge-config-ui-x][0m [31mSyntaxError: Unexpected token %[0m

/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:22227
flatstr(payload)
^
SyntaxError: Unexpected token %
at preserializeHookEnd (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:22227:3)
at preserializeHook (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:22216:5)
at _Reply.Reply.send (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:22115:5)
at PassThrough.flush [as _flush] (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:73169:17)
at PassThrough.prefinish (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:34606:10)
at PassThrough.emit (events.js:196:13)
at prefinish (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:34395:14)
at finishMaybe (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:34404:5)
at endWritable (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:34417:3)
at PassThrough.Writable.end (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:34355:22)
at SendStream.notModified (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:75462:7)
at SendStream.send (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:75720:12)
at onstat (/usr/lib/node_modules/homebridge-config-ui-x/dist/main.js:75812:10)
at FSReqCallback.oncomplete (fs.js:149:5)`

**Comment by hangmanandhide** [comment] 2019-05-29 22:19
I just got this as well: [homebridge-config-ui-x] SyntaxError: Unexpected token %

after logging into the ui-x for the first time, I tried clickign plugins and it triggered that in terminal. I then tried to click config and it wouldn't let me. Clicking log seemed to work, although it was blank...

every other button on the menu seemed to throw the error as well -- except restart which gave
[homebridge-config-ui-x] SyntaxError: Unexpected token %

followed by 3 lines of the unexpected token % error...

**Comment by marcoschmidt79** [comment] 2019-05-29 22:22
yes, same problem, also with 4.4.3

**Comment by oznu** [comment] 2019-05-29 22:26
I've not been able to figure this one out.

I got it once on a fresh Raspberry Pi install, but as soon as I added some trivial debug code and restarted I could not replicate the problem again, even after reinstalling and removing the debug code.

**Comment by marcoschmidt79** [comment] 2019-05-29 22:34
> I've not been able to figure this one out.
> 
> I got it once on a fresh Raspberry Pi install, but as soon as I added some trivial debug code and restarted I could not replicate the problem again, even after reinstalling and removing the debug code.

How many instaces do you have? i think, this is a problem when you have more than one instances

**Comment by oznu** [comment] 2019-05-29 22:49
One thing you might be able to try is added `"debug": true` to the UI config.

Then as a second test start Homebridge with the `DEBUG=*` environment variable. This is going to generate a lot of logs, so just post the bits around where the error occurs.

**Comment by marcoschmidt79** [comment] 2019-05-29 22:53
ok, i will do it on the next days and i post the logs :-)

**Comment by oznu** [comment] 2019-05-30 07:47
I don't think multiple instances is the cause:

![image](https://user-images.githubusercontent.com/3979615/58617155-c16f9780-8302-11e9-88cb-7f5c1d58232d.png)

I setup 10 instances of homebridge running the config plugin on a Raspberry Pi 3 managed by `systemd`.

**Comment by oznu** [comment] 2019-05-30 10:24
I've found the only function in the code base that was not logging it's error correctly (with a full stack trace). If you try 4.4.4 I think the error should be much more detailed.

**Comment by oznu** [comment] 2019-05-30 11:26
Next thing to try...

```
npm install -g --unsafe-perm homebridge-config-ui-x@next
```

**Comment by marcoschmidt79** [comment] 2019-05-30 15:01
> Next thing to try...
> 
> ```
> npm install -g --unsafe-perm homebridge-config-ui-x@next
> ```

Yes, thank you very much, the 4.4.5 beta 1 works fine without syntax error. :-D

**Comment by oznu** [comment] 2019-06-02 03:03
I've published 4.4.5. You can upgrade from the beta version in-app.

@marcoschmidt79 - if there are still no problems feel free to close this issue 😄

**Closed** 2019-06-02 08:57 UTC
Labels: bug
