### ISSUE TITLE
Homebridge UI plugin menu items for some plugins missing

### ISSUE THREAD

**Issue by jsiegenthaler** [oznu/homebridge-config-ui-x#2070] opened 2024-06-22 05:19 UTC
### Describe The Bug

Some recently published plugins are missing the **Manage Version** and **Report An Issue** items in the plugin menu, and the author name is missing beside the @ symbol.
You can still click on the @ symbol to display the Donate to window, but the @ in front of the author name is missing.

Normal display of menu items and author name:
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/59387202/5bfbedc3-8132-416f-a386-1cccc84d2423)

Plugin missing the menu items and author name:
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/59387202/fd804f00-54b2-46ce-b4dc-969e3190a145)
This is particularly problematic as the user cannot change to another plugin version due to the missing **Manage Version** item

Normal display of **Donate to**:
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/59387202/a49e60de-fd14-4219-a093-62311e0b2d33)

Display of **Donate to** for a plugin where the author name is missing:
![image](https://github.com/homebridge/homebridge-config-ui-x/assets/59387202/87170c69-753f-4a16-8e99-b80070632c64)

You can still click on the single @ character to open the **Donate to** window

### Homebridge UI Version

4.56.2

### Homebridge Version

1.8.3

### Node.js Version

20.14.0

### Operating System

Raspberry Pi OS / Raspbian

### Environment Info

Using hb-service

### Raspberry Pi Model

Raspberry Pi 4 B

**Comment by grzegorz914** [comment] 2024-06-22 05:22
Same for me, I think it is related to #2069

**Comment by jsiegenthaler** [comment] 2024-06-22 05:24
Additionally: newer published versions are now shown as being available, the user has no visibility of any updates.
WS has a new release but it does not appear as an available update:
https://github.com/ebaauw/homebridge-ws/releases/tag/v2.7.23

**Comment by jsiegenthaler** [comment] 2024-06-22 05:41
> Same for me, I think it is related to #2069

Indeed, I observe the following for my affected plugin in my dev environment:
`[22.06.2024, 07:37:48] [Homebridge UI] [homebridge-eosstb] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.`

**Comment by mkz212** [comment] 2024-06-22 20:58
@donavanbecker @bwp91  We cannot update Homebridge UI , you need to add manualy in package.json `"maintainers": ["maintainer-name"]` and release new version with latest tag. Without this we have error: `[Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.`

**Comment by mkz212** [comment] 2024-06-22 20:59
@jsiegenthaler @grzegorz914 you need to add manualy in package.json `"maintainers": ["maintainer-name"]` and release new version with latest tag. In new Homebridge UI it will be solved.

**Comment by mkz212** [comment] 2024-06-22 21:13
@jsiegenthaler @grzegorz914 you need to add manualy in plugin package.json `"maintainers": ["maintainer-name"]` and release new version with latest tag. This is because NPM stop adding this automatically to release. Homebridge UI check author (maintainer) from latest release and now it is empty. New UI version fix this.

**Comment by dkerr64** [comment] 2024-06-22 23:15
That NPM has stopped adding maintainers field feels like a bug in NPM and should be fixed there.  The [NPM Documentation](https://docs.npmjs.com/cli/v10/configuring-npm/package-json) does not document a "maintainers" field but explicitly states... _"npm also sets a top-level "maintainers" field with your npm user info."_ 

In addition, the npmjs.com package settings page lists maintainers and allows you to invite another person to be added as a maintainer... all done outside of the package.json source file.

If this is the documented behavior, then it's a bug in NPM that it has stopped adding this field.

**Comment by dkerr64** [comment] 2024-06-22 23:19
And over [here](https://github.com/npm/www/issues/133#issuecomment-284906561) npm states themselves...

_"The "maintainers" field in the top-level of the registry metadata (ie, not versioned) is the **npm-controlled** list of the npm usernames of the people with permission to write to that package. This can be modified via the npm owners command."_ (emphasis mine).

So I believe that it is not correct to recommend adding maintainers field to each package.json file.

**Comment by mkz212** [comment] 2024-06-23 01:37
@dkerr64 

- NPM always add maintainers to package, now stopped.
- Homebridge had a bug that checked maintainers.lenght before checking if it exists at all. It was fixes. #2069 
- Homebridge check maintainers from latest stable release of plugin, and first of maintainers you see on plugin card next to heart icon.
- So if plugin doesnt have any new release since 2-3 days (since npm does not add maintainers), everything works.

To summarize:

- NPM error is that it does not add maintainers (since couple days).
- The Homebridge UI error was that it checked how many maintainers, without checking if they were at all exist. And this suspended all npm functions, also responsible for checking the version, etc. If it weren't for that, the NPM error would only cause that there would be no author on the plugin card (only a heart icon and a @ sign because it is hardcoded).

So adding maintainers to package.json is only workaround until Homebridge UI and NPM fix errors.

**Comment by dkerr64** [comment] 2024-06-23 14:40
@mkz212 yes good summary... I was working on my plugin and noticed the problem, I tracked it down to checking the length statement then discovered that it had just been fixed, so all good from Homebridge side.

I do think that NPM need to fix their bug. Is there a bug report open?

**Comment by solomonj1963** [comment] 2024-06-23 16:58
I believe the issue I just experienced may be related to this.  I set up the Homebridge Simplisafe3 by @nzapponi yesterday and tested arming and disarming my alarm through a HomeKit scene successfully.  This morning I ran my scene that should have turned the alarm off, but found out it had not when the security company called because the alarm went off when it should have been turned off 4 hours ago by my HomeKit scene.  Looking at the plugin log, all I see is this:  

[6/22/2024, 12:44:14 AM] [Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[6/22/2024, 12:44:16 AM] [Alarm] Sensor not (yet) supported: Back Yard
[6/22/2024, 12:44:16 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f8614',
  type: 17,
  name: 'Back Yard',
  setting: {},
  status: {},
  timestamp: 1693369208,
  deviceGroupID: 0
}
[6/22/2024, 12:44:16 AM] [Alarm] Sensor not (yet) supported: Front Door
[6/22/2024, 12:44:16 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f927c',
  type: 17,
  name: 'Front Door',
  setting: {},
  status: {},
  timestamp: 1693369562,
  deviceGroupID: 0
}
[6/22/2024, 12:44:16 AM] [Alarm] SimpliSafe real time events connected.
[6/22/2024, 12:45:34 AM] [Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[6/22/2024, 12:45:35 AM] [Alarm] Sensor not (yet) supported: Back Yard
[6/22/2024, 12:45:35 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f8614',
  type: 17,
  name: 'Back Yard',
  setting: {},
  status: {},
  timestamp: 1693369208,
  deviceGroupID: 0
}
[6/22/2024, 12:45:35 AM] [Alarm] Sensor not (yet) supported: Front Door
[6/22/2024, 12:45:35 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f927c',
  type: 17,
  name: 'Front Door',
  setting: {},
  status: {},
  timestamp: 1693369562,
  deviceGroupID: 0
}
[6/22/2024, 12:45:35 AM] [Alarm] Detected unsupported camera Back Yard, some features will be disabled.
[6/22/2024, 12:45:35 AM] [Alarm] Detected unsupported camera Front Door, some features will be disabled.
[6/22/2024, 12:45:36 AM] [Alarm] SimpliSafe real time events connected.
[6/22/2024, 12:46:14 AM] [Alarm] Initializing homebridge-simplisafe3.SimpliSafe 3 platform...
[6/22/2024, 12:46:15 AM] [Alarm] Sensor not (yet) supported: Back Yard
[6/22/2024, 12:46:15 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f8614',
  type: 17,
  name: 'Back Yard',
  setting: {},
  status: {},
  timestamp: 1693369208,
  deviceGroupID: 0
}
[6/22/2024, 12:46:15 AM] [Alarm] Sensor not (yet) supported: Front Door
[6/22/2024, 12:46:15 AM] [Alarm] {
  flags: { offline: false, lowBattery: false, swingerShutdown: false },
  serial: 'f10f927c',
  type: 17,
  name: 'Front Door',
  setting: {},
  status: {},
  timestamp: 1693369562,
  deviceGroupID: 0
}
[6/22/2024, 12:46:15 AM] [Alarm] SimpliSafe real time events connected.

However, the Homebridge log shows the following occurring afterwards.  

[6/22/2024, 1:10:08 AM] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[6/22/2024, 2:42:42 AM] [Homebridge UI] Running scheduled instance backup...
[6/22/2024, 2:42:42 AM] [Homebridge UI] Creating temporary backup archive at /var/folders/zn/gzbnx7mj0c1_kmm0h0ngm9hm0000gn/T/homebridge-backup-EMm0dT/homebridge-backup-0ECEF6C38D83.tar.gz
[6/23/2024, 1:10:11 AM] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[6/23/2024, 2:42:42 AM] [Homebridge UI] Running scheduled instance backup...
[6/23/2024, 2:42:42 AM] [Homebridge UI] Creating temporary backup archive at /var/folders/zn/gzbnx7mj0c1_kmm0h0ngm9hm0000gn/T/homebridge-backup-etcwtG/homebridge-backup-0ECEF6C38D83.tar.gz
[6/23/2024, 2:42:42 AM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[6/23/2024, 12:35:36 PM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[6/23/2024, 12:35:36 PM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
[6/23/2024, 12:42:42 PM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.

I have now tested arming and disarming using my HomeKit scene and it appears to be working now.  I cannot find an explanation as to why the Good Morning scene that turns the alarm off did not run 4 hours ago as it should have.  I would appreciate any insight.

**Comment by zivanek** [comment] 2024-06-23 18:55
I have the same problem, all day

**Comment by mkz212** [comment] 2024-06-23 21:13
> @mkz212 yes good summary... I was working on my plugin and noticed the problem, I tracked it down to checking the length statement then discovered that it had just been fixed, so all good from Homebridge side.
> 
> I do think that NPM need to fix their bug. Is there a bug report open?

https://github.com/orgs/community/discussions/129220

**Comment by mkz212** [comment] 2024-06-23 21:15
> I have the same problem, all day

To fix error in plugin you need to add manualy in plugin package.json `"maintainers": ["maintainer-name"]` and release new version with latest tag. This is because NPM stop adding this automatically to release. Homebridge UI check author (maintainer) from latest release and now it is empty. New Homebridge UI version will fix this.

**Comment by mkz212** [comment] 2024-06-23 21:23
@solomonj1963 Everyone now have error `[homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')"`. This has nothing to do with controling the plugin. It is caused by a problem with NPM. And the fact that the new version of Homebridge UI does not have 'maintainers' in package.json.

**Comment by mkz212** [comment] 2024-06-23 21:25
@donavanbecker @bwp91  

- We cannot update Homebridge UI.
- You need to add manualy in package.json `"maintainers": ["maintainer-name"]` and release new version with latest tag. 
- Without this we have error: `[Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.`

**Comment by NorthernMan54** [comment] 2024-06-23 22:32
@mkz212 Can you elaborate on this comment - _We cannot update Homebridge UI._

I just went and updated mine and had no issues.

**Comment by mkz212** [comment] 2024-06-24 02:04
@NorthernMan54 

I have UI 4.56.2, so the last version before fix. 

It shows me error in logs: `[Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.`. 

This is because latest release of Homebridge UI - 4.56.3 has no maintainers in package.json. 

So it doesn't show me update option. 

Version 4.56.2 check lenght of maintainers but not check first that maintainers exist. And in 4.56.3 maintainers not added to package.json so doesnt exist.

**Comment by donavanbecker** [comment] 2024-06-24 02:10
if you have UI 4.56.2 then you are not on the latest. v4.56.3 has the fix for this, this is resolved.

**Closed as completed by donavanbecker** 2024-06-24 02:10 UTC
Labels: bug

**Comment by mkz212** [comment] 2024-06-24 02:13
> if you have UI 4.56.2 then you are not on the latest. v4.56.3 has the fix for this, this is resolved.

Yes. I know. But we cannot update to 4.56.3 because you release it with package.json without maintainers. So now every version before 4.56.3 check for the maintainers lenght from the latest release what produce error because there is NO maintainers in latest release!

Why closind Issue when users report that still have errors?

If before npm always automatically added maintainers to the package, and now it stopped and this causes a problem, why not just add maintainers yourself and publish? Is it a problem?

**Comment by NorthernMan54** [comment] 2024-06-24 02:27
@mkz212 I just went into the UI and selected 4.56.3

**Comment by mkz212** [comment] 2024-06-24 02:31
@donavanbecker @NorthernMan54  

Oh, okay, I already know what it's about and why we don't understand each other. I mean that there is a error in the logs (and users dont know what is it) and that the update notification does not pop up. So users do not know there is fix. 

Not everyone knows that you have to click on the Homebridge UI text on the widget to open the version selection window - It's not so obvious, because most people are used to the notification shows up!

**Comment by ImpulsePurchase** [comment] 2024-06-24 03:36
That's right @mkz212.  I'm a fairly experienced homebridge user I think, but I was surprised to see there was a later version under the install dialog, with 'Up to Date' as the status for Homebridge UI.

**Comment by mkz212** [comment] 2024-06-24 03:40
> That's right @mkz212. I'm a fairly experienced homebridge user I think, but I was surprised to see there was a later version under the install dialog, with 'Up to Date' as the status for Homebridge UI.

That's what I mean! Everyone is so used to the fact that a notification about the update shows up that no one even knows that there is an option to install the selected version after you click on Homebridge UI text. BTW: such an option to instalk other version should also be in settings / UI settings.

**Comment by oogje** [comment] 2024-06-24 03:53
I'm sorry to be so dense but I cannot see any clickable Homebridge UI text.  I have homebridge-config-ui-x v4.52.2 but neither the "Homebridge UI" text in the Plugins window nor the "homebridge-config-ui-x v4.52.2" text is clickable.  And the only entry in Homebridge UI vertical ellipses menu is "API Documentation".

How do I install homebridge-config-ui-x v4.52.3.

Thanks.
<img width="651" alt="Screenshot 2024-06-23 at 11 51 48 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/1358680/16e0851d-ec6c-4cf6-bb3e-704cc1bfe2ee">

**Comment by mkz212** [comment] 2024-06-24 03:56
@oogje 

In Status tab (there where you have widgets and qr code). 

![IMG_6218](https://github.com/homebridge/homebridge-config-ui-x/assets/82271669/5cab813a-176b-41f8-b221-a1e495a490a1)

**Comment by ImpulsePurchase** [comment] 2024-06-24 03:56
@oogje Good Question.  It's from the Status Page in a box that looks like this
<img width="261" alt="image" src="https://github.com/homebridge/homebridge-config-ui-x/assets/172002020/d3f67a10-0f0c-4d6e-9116-8fdef3db06e9">

**Comment by oogje** [comment] 2024-06-24 04:00
Alas, my status page doesn't look like that - no Homebridge UI text.  macOS 14.5, Safari 17.5.
<img width="1586" alt="Screenshot 2024-06-23 at 11 58 49 PM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/1358680/47ad1410-397b-46b8-909f-ad9019d2119a">

**Comment by mkz212** [comment] 2024-06-24 04:01
For everyone with such problem - you can update by clicking on Homebridge UI text. 



> Alas, my status page doesn't look like that - no Homebridge UI text. macOS 14.5, Safari 17.5. <img alt="Screenshot 2024-06-23 at 11 58 49 PM" width="1586" src="https://private-user-images.githubusercontent.com/1358680/342197182-47ad1410-397b-46b8-909f-ad9019d2119a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDE5MzgsIm5iZiI6MTcxOTIwMTYzOCwicGF0aCI6Ii8xMzU4NjgwLzM0MjE5NzE4Mi00N2FkMTQxMC0zOTdiLTQ2YjgtOTA5Zi1hZDkwMTlkMjExOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDQwMDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU5ZWM2ZDllMjkxOWZkMTBhZTgyMzk1MmQ3YTUyMzcyZmEzMjgzMWZkYmQ2MDg1ZmEyZjJmMWQwODc5MmJhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o2-6FVWMfOYgSzQN9F-f3GrVfOEpcSeuKl-o70xnAt8">

Click on the icon on the bottom right (in circle) to manage view and add widget. You can also reset view to default.

BTW this is another reason to add version selection to the settings or UI settings!

**Comment by oogje** [comment] 2024-06-24 04:05
I'm sorry if I'm derailing this issue but I don't see a status widget other than the one in my previous screenshot.  I don't have a child bridge.

<img width="856" alt="Screenshot 2024-06-24 at 12 03 04 AM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/1358680/51d53b73-ed17-44a9-9336-bf63170d5e8f">


After reset layout...
<img width="1465" alt="Screenshot 2024-06-24 at 12 06 42 AM" src="https://github.com/homebridge/homebridge-config-ui-x/assets/1358680/b24b935d-c744-4f23-926a-9ba943335a7e">

**Comment by mkz212** [comment] 2024-06-24 04:07
@oogje click reset layout (you already have this widget but i think it is cropped somehow)

**Comment by oogje** [comment] 2024-06-24 04:08
@mkz212 , I edited my last comment to show the reset layout.

**Comment by mkz212** [comment] 2024-06-24 04:13
@oogje hmm... this is strange. It should be there. So this is a bug. 

You can also try run terminal (in Homebridge, not mac os terminal) and type: `npm install -g homebridge-config-ui-x@4.56.3`

**Comment by oogje** [comment] 2024-06-24 04:15
@mkz212  Will do.  Thank you!

**Comment by zivanek** [comment] 2024-06-24 07:11
Thank you guys I updated to version v4.56.3 manually because homebridge didnt't offer me an option to update automatically.
![Screenshot 2024-06-24 at 09 05 42](https://github.com/homebridge/homebridge-config-ui-x/assets/17454593/21f34241-c2b2-483e-a439-987da950eeab)

**Comment by NorthernMan54** [comment] 2024-06-24 13:06
@mkz212 - In regards to the "maintainers" field with package.json, as it is documented as being supplied by npm, and not a user supplied field, lets wait and see what happens on the npm side over the next few days.  I expect that is an issue with a recent release on their side, and would expect it to be resolved by them within a few days.

**Comment by dkerr64** [comment] 2024-06-24 13:45
> @oogje hmm... this is strange. It should be there. So this is a bug.
> 
> You can also try run terminal (in Homebridge, not mac os terminal) and type: `npm install -g homebridge-config-ui-x@4.56.3`

If you install homebridge as documented [here](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux), then npm is not available...

```
root@test:~# npm
Command 'npm' not found, but can be installed with:
apt install npm
root@test:~#
```

I do not know if it is safe to install npm as that looks to drag a whole nodejs environment, which may be different from that included with homebridge (it says 527 new packages will be installed !!!)

Bottom line, we shouldn't require command line to update this plugin.

**Comment by dkerr64** [comment] 2024-06-24 13:46
> @mkz212 - In regards to the "maintainers" field with package.json, as it is documented as being supplied by npm, and not a user supplied field, lets wait and see what happens on the npm side over the next few days. I expect that is an issue with a recent release on their side, and would expect it to be resolved by them within a few days.

I agree.

**Comment by PatrickStankard** [comment] 2024-06-24 15:17
I opened a support ticket with NPM on Thursday, along with [this thread](https://github.com/orgs/community/discussions/129220) on GitHub Community (which is what they say to do when giving feedback, according to [this](https://www.npmjs.com/support)). If anyone wants to chime in on that thread, or upvote it, or whatever, it might get them to investigate it sooner rather than later

**Comment by NorthernMan54** [comment] 2024-06-24 15:20
Upvoted

**Comment by solomonj1963** [comment] 2024-06-24 15:24
I'm glad this is figured out and my instance is fixed now.  However, I would like to point out that, due to the notification "bug", there are probably still thousands of installations out there where the person is not even aware of it.  I was not aware of it until my alarm monitoring company called me for tripping my alarm when it should have been turned off via HomeKit but wasn't.  I'd like to point out that sometimes the impact of a bug can be larger than the developers realize, and I'm concerned that there needs to be a method developed to make sure existing users do get notified and apply the update.  I don't believe saying this is completed is really true, as a manual fix has been identified and only known to people who find this discussion.  With all due respect, I believe something creative should be implemented to assure every user is notified of the update that has been lurking in the shadows.  I appreciate everything all you developers do for us, I truly do!  But unless I'm missing something here, this missing notification remains a high impact bug and people are still not being notified.

**Comment by dkerr64** [comment] 2024-06-24 15:26
> I opened a support ticket with NPM on Thursday, along with [this thread](https://github.com/orgs/community/discussions/129220) on GitHub Community (which is what they say to do when giving feedback, according to [this](https://www.npmjs.com/support)). If anyone wants to chime in on that thread, or upvote it, or whatever, it might get them to investigate it sooner rather than later

There is zero discussion on that thread... which is rather discouraging after 4 days for something that will impact 1000's of packages.

**Comment by PatrickStankard** [comment] 2024-06-24 15:33
@solomonj1963 this bug is only related to the Homebridge UI asynchronously checking for updates on existing packages, it wouldn't have any impact on the functionality of the plugins themselves

**Comment by mkz212** [comment] 2024-06-24 15:42
> @solomonj1963 this bug is only related to the Homebridge UI asynchronously checking for updates on existing packages, it wouldn't have any impact on the functionality of the plugins themselves

If you have UI v.4.56.2 or below, for every plugin that doesn't have maintainers in package.json in latest release, you cannot update plugin and cannot access 'Instal other version' in plugin menu. So some impact is...

**Comment by PatrickStankard** [comment] 2024-06-24 15:45
That is true! I just wanted to clarify because I don't think this bug had anything to do with what was being described in [this comment](https://github.com/homebridge/homebridge-config-ui-x/issues/2070#issuecomment-2185153258)

**Comment by solomonj1963** [comment] 2024-06-24 15:46
> @solomonj1963 this bug is only related to the Homebridge UI asynchronously checking for updates on existing packages, it wouldn't have any impact on the functionality of the plugins themselves

Thank you for the response.  I hope you are correct with that.  In my case, all I can say is that I had a "Good Morning" scene which included setting my Simplisafe alarm system to off.  The same scene triggers alot of other activity around my home that did occur.  The only device used in that scene that is on my homebridge instance is the Simplisafe system.  I had nothing showing in any of my logs that homebridge or my plugins saw that I had activated that scene.  Other devices on my home-assistant platform did see it and acted as expected.  So, I'm not complaining, but I feel like this was a big gap in my instance and it is within reason it could be for others.  I'm only recommending a little more thought be invested on this potential impact.

**Comment by dkerr64** [comment] 2024-06-24 15:54
> > @solomonj1963 this bug is only related to the Homebridge UI asynchronously checking for updates on existing packages, it wouldn't have any impact on the functionality of the plugins themselves
> 
> If you have UI v.4.56.2 or below, for every plugin that doesn't have maintainers in package.json in latest release, you cannot update plugin and cannot access 'Instal other version' in plugin menu. So some impact is...

The problem is even worse, because the UI 4.56.2 and below are not detecting that there is a new UI release.  To test, I just installed hombridge following instructions [here](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux).  And it installed UI v4.56.2 and reports that it is up-to-date...

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/17837612/a45cf626-995a-4a4a-9f46-3017ec386702)

![image](https://github.com/homebridge/homebridge-config-ui-x/assets/17837612/b3371535-722b-439b-a1d8-ef6982717c78)

So your average user has no idea that the Homebridge UI is out-of-date, AND will not get any prompting for ANY other plugin that has had an update published.... unless the plugin owner adds the maintainers list to their package.json.

And... this UI needs to add it to its own package.json, which will hopefully then cause homebridge to highlight that a new UI is available.

**Comment by dkerr64** [comment] 2024-06-24 16:03
Opened #2076 as this one is closed.
