### ISSUE TITLE
Can you add instances?

### ISSUE THREAD

**Issue by m4d-maNu** [oznu/homebridge-config-ui-x#17] opened 2018-01-22 13:56 UTC
Hello,
Can you add multiple instances of the Homebridge to this plugin?

Greeting Manu

**Comment by oleg77s** [comment] 2018-01-22 18:44
There are 3 nstances of the Homebridge on  my RPI Zero W:
homebridge.service  (homebridge-pi, homebridge-platform-wemo, homebridge-mi-aqara 
       and miio homebridge-mi-outlet plugins)     
homebridgehhub.service (harmony-hub plugin)
homebridgehue.service (homebridge-hue plugin)

And i also interested in this feature

**Comment by oznu** [comment] 2018-01-23 09:23
Thanks for your question. Currently you cannot have a single instance of the plugin managing multiple instances of Homebridge.

While a single instance of the UI could connect to multiple Homebridge instances relatively easily, each instance of Homebridge would still require the plugin to be installed to serve the api endpoints required to send data back to the UI.

It would be quite a bit of work to make this happen, but I welcome any contributions/pull requests that can implement this in a user friendly and secure way.

**Comment by oleg77s** [comment] 2018-01-23 12:12
This plugin only work if  systemd service has the name homebridge ?
Temporary solution: add choice  a name  of homebridge service  in config and start for each instances its own plugin with different name, path and port.
And each instances will be available to the address  http://localhost:port

**Comment by oznu** [comment] 2018-01-23 12:51
@oleg77s I'll add the option to customise the systemd service name in the next few days. 

In the mean time you can use the "log from custom command" option to get the logs of any systemd service:

https://github.com/oznu/homebridge-config-ui-x#logs-from-custom-command

The command that gets run when you have log set to systemd is:

```
journalctl -o cat -n 500 -f -u homebridge
```

Customise to suite.

**Comment by oleg77s** [comment] 2018-01-23 18:06
No log file in browser :(
Safari: http://192.168.0.172:8080/config

Log file does not exist: journalctl -o cat -n 500 -f -u homebridgehue
Please set the correct path to the logs in your Homebridge config.json file.

Config:
{
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "restart": "sudo -n systemctl restart homebridge",
            "log": "journalctl -o cat -n 500 -f -u homebridgehue",
            "sudo": true
        }

from  terminal its ok:
pi@Pi84-0W:/ $ journalctl -o cat -n 500 -f -u homebridge
[2018-1-23 20:19:49] [MiOutletPlatform] Initializing platform accessory 'WC plug'...
[2018-1-23 20:19:49] [MiOutletPlatform] Initializing platform accessory 'WC plug T'...
[2018-1-23 20:19:49] [MiOutletPlatform] Initializing platform accessory 'WC usb ночник'...
[2018-1-23 20:19:49] [MiAqaraPlatform] Initializing MiAqaraPlatform platform...
[2018-1-23 20:19:49] [MiAqaraPlatform] [INFO]**************************************************************
--------------------
[2018-1-23 20:19:49] [MiAqaraPlatform] [INFO]           MiAqaraPlatform v0.6.8 By YinHang
Load homebridge-harmonyhub.HarmonyHub
................

**Comment by oznu** [comment] 2018-01-24 00:45
@oleg77s the correct syntax for logs from custom command is:

```json
{
        "platform": "config",
        "name": "Config",
        "port": 8080,
        "restart": "sudo -n systemctl restart homebridgehue",
        "log": {
             "tail": "sudo -n journalctl -o cat -n 500 -f -u homebridgehue"
         },
        "sudo": true
}
```

**Comment by oleg77s** [comment] 2018-01-24 05:43
Something wrong with permission:

Using custom command to tail logs
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge
chdir(2) failed.: Permission denied

The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
Please check the command in your config.json is correct.


{
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "restart": "sudo -n systemctl restart homebridge",
            "log": {
                "tail": "sudo -n journalctl -o cat -n 500 -f -u homebridge"
            },
            "sudo": true
        },

**Comment by oznu** [comment] 2018-01-24 05:50
If the command works from the terminal, then the same command should work using the [Logs from custom command](https://github.com/oznu/homebridge-config-ui-x#logs-from-custom-command) setting. All the app does is spawn a pseudo terminal and execute the command.

**Comment by oznu** [comment] 2018-01-24 06:55
As promised, I added support for custom `systemd` service names.

```json
"platform":[
    {
      "platform": "config",
      "name": "Config",
      "port": 8080,
      "log": {
          "systemd": "homebridge-two"
       },
       "sudo": "true"
    }
]
```

**Comment by oleg77s** [comment] 2018-01-24 13:37
custom systemd service names works just fine :)

homebridge on port 8080
homebridgehhub on port 808
homebridgehue on port 8082

Configs ann reboots are OK

Thanks

--------
the command 
sudo -n journalctl -o cat -n 500 -f -u homebridge
works from the terminal, not from UI :(

**Comment by oznu** [comment] 2018-01-27 06:26
Closing this as the original question has been answered and a work-around provided.

**Closed by oznu** 2018-01-27 06:26 UTC
Labels: enhancement

**Comment by DarthCruiser** [comment] 2018-04-05 23:02
Hi,
I have 3 instances of homebridge running on my Debian server and I have setup mostly as described above and log into each instance separately.

To achieve this I have 3 x QR Codes, 3 x homebridge port numbers, 3 x Config UI x port numbers, 3 x Systemd Service Scripts, 3 x Environment scripts defining - 3 x unique locations for config.json files and 3 x unique locations for plugins (the Config UI plugin was copied over and exists in all 3 plugin locations). By design my intended setup is 3 x completely isolated homebridge instances. 

I am running as root user intentionally so have not seen any issues with logs or file/folder permissions. In fact everything looks to be working very well.

My question is - when I install a plugin in the future using one of the instances of Config UI x, is the plugin installed to the location specified by the -P option in the service environment scripts for that instance, or will all plugins be installed to a single location and need to be moved manually? ... and if so, are plugins installed/removed in one instance of Config UI x visible in all?

I would just like to clarify as multi-instance behaviour of Config UI x is not documented in detail regarding plugin management between instances.

**Comment by DarthCruiser** [comment] 2018-04-06 07:14
Good Morning @oznu - thanks for the information, you have provided some useful steers regarding directory structure. 

I currently have the plugins at node /usr/lib/node_modules2 etc. However, this is easy to change to /usr/lib/2/node_modules etc and automatically updating package.json will be useful so I am very pleased this functionality is built in and I will do this.

My approach will be to uninstall/reinstall all plugins via conf-ui-x and keep everything local. I plan to make conf-ui-x the central point for plugin co-ordination for each homebridge instance, so its good to feel there is a good level of support for this.

I will let you know how I go on and may have a couple of additional questions - speak soon @oznu, I hope you have good weather in your part of the world.

**Comment by bohtho** [comment] 2018-05-14 17:56
I have to services homebridge.service and homebridge-ext.service with different globally installed plugins in their config files, except both having config-x in their config.json (with different colour, port numbers and different systemd log reference). But the latest added services won't load the config-x web page?

**Comment by oznu** [comment] 2018-05-15 11:06
@bohtho, there should be no issues running multiple instances of the plugin as long as they are listening on different ports. Is there anything in the journald logs that might explain what's going on - feel free to paste them here if you want me to check them.

**Comment by bohtho** [comment] 2018-05-15 16:49
My second homebridge service is called homebridge-ext. I don't understand why it tries to load homebridge-hue which is not part of its config.json or its local node_modules directory. Anyway, there's no reaction from its config-x with another port number either.

`root@LillePi:/etc/default# systemctl enable homebridge-ext.service 
Created symlink /etc/systemd/system/multi-user.target.wants/homebridge-ext.service → /etc/systemd/system/homebridge-ext.service.
root@LillePi:/etc/default# systemctl start homebridge-ext.service 
root@LillePi:/etc/default# journalctl -f -u homebridge-ext`

`May 15 18:42:33 LillePi node[29416]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
May 15 18:42:33 LillePi node[29416]: *** WARNING *** Please fix your application to use the native API of Avahi!
May 15 18:42:33 LillePi node[29416]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
May 15 18:42:34 LillePi homebridge[29416]: [2018-5-15 18:42:34] Loaded plugin: homebridge-dacp
May 15 18:42:34 LillePi homebridge[29416]: [2018-5-15 18:42:34] Registering platform 'homebridge-dacp.DACP'
May 15 18:42:34 LillePi homebridge[29416]: [2018-5-15 18:42:34] ---
May 15 18:42:34 LillePi homebridge[29416]: [2018-5-15 18:42:34] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.11.1 which does not satisfy the current Node version of v9.9.0. You may need to upgrade your installation of Node.
May 15 18:42:35 LillePi homebridge[29416]: [2018-5-15 18:42:35] Loaded plugin: homebridge-hue
May 15 18:42:35 LillePi homebridge[29416]: [2018-5-15 18:42:35] Registering platform 'homebridge-hue.Hue'
May 15 18:42:35 LillePi homebridge[29416]: [2018-5-15 18:42:35] ---
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] Loaded plugin: homebridge-mqtt
May 15 18:42:36 LillePi homebridge[29416]: homebridge API version: 2.2
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] Registering platform 'homebridge-mqtt.mqtt'
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] ---
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] Loaded config.json with 0 accessories and 1 platforms.
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] ---
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] Loading 1 platforms...
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] [Config] Initializing config platform...
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] Loading 0 accessories...
May 15 18:42:36 LillePi homebridge[29416]: Load homebridge-mqtt.mqtt
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] [homebridge-mqtt.mqtt] config undefined or null!
May 15 18:42:36 LillePi homebridge[29416]: [2018-5-15 18:42:36] [homebridge-mqtt.mqtt] storagePath = /var/lib/homebridge-ext
May 15 18:42:36 LillePi systemd[1]: homebridge-ext.service: Main process exited, code=exited, status=1/FAILURE
May 15 18:42:36 LillePi systemd[1]: homebridge-ext.service: Unit entered failed state.
May 15 18:42:36 LillePi systemd[1]: homebridge-ext.service: Failed with result 'exit-code'.
May 15 18:42:46 LillePi systemd[1]: homebridge-ext.service: Service hold-off time over, scheduling restart.
May 15 18:42:46 LillePi systemd[1]: Stopped Node.js HomeKit Server Ext.
May 15 18:42:46 LillePi systemd[1]: Started Node.js HomeKit Server Ext.
May 15 18:42:49 LillePi homebridge[29463]: [2018-5-15 18:42:49] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/var/lib/homebridge-ext/node_modules/homebridge-config-ui-x'.
May 15 18:42:49 LillePi homebridge[29463]: [2018-5-15 18:42:49] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-dacp' since we already loaded the same plugin from '/var/lib/homebridge-ext/node_modules/homebridge-dacp'.
May 15 18:42:49 LillePi homebridge[29463]: [2018-5-15 18:42:49] Loaded plugin: homebridge-config-ui-x
May 15 18:42:49 LillePi homebridge[29463]: [2018-5-15 18:42:49] Registering platform 'homebridge-config-ui-x.config'
May 15 18:42:49 LillePi homebridge[29463]: [2018-5-15 18:42:49] ---
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** Please fix your application to use the native API of Avahi!
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** Please fix your application to use the native API of Avahi!
May 15 18:42:49 LillePi homebridge[29463]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
May 15 18:42:49 LillePi node[29463]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
May 15 18:42:49 LillePi node[29463]: *** WARNING *** Please fix your application to use the native API of Avahi!
May 15 18:42:49 LillePi node[29463]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
May 15 18:42:49 LillePi node[29463]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
May 15 18:42:49 LillePi node[29463]: *** WARNING *** Please fix your application to use the native API of Avahi!
May 15 18:42:49 LillePi node[29463]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
May 15 18:42:50 LillePi homebridge[29463]: [2018-5-15 18:42:50] Loaded plugin: homebridge-dacp
May 15 18:42:50 LillePi homebridge[29463]: [2018-5-15 18:42:50] Registering platform 'homebridge-dacp.DACP'
May 15 18:42:50 LillePi homebridge[29463]: [2018-5-15 18:42:50] ---
May 15 18:42:50 LillePi homebridge[29463]: [2018-5-15 18:42:50] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.11.1 which does not satisfy the current Node version of v9.9.0. You may need to upgrade your installation of Node.
May 15 18:42:51 LillePi homebridge[29463]: [2018-5-15 18:42:51] Loaded plugin: homebridge-hue
May 15 18:42:51 LillePi homebridge[29463]: [2018-5-15 18:42:51] Registering platform 'homebridge-hue.Hue'
May 15 18:42:51 LillePi homebridge[29463]: [2018-5-15 18:42:51] ---
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] Loaded plugin: homebridge-mqtt
May 15 18:42:52 LillePi homebridge[29463]: homebridge API version: 2.2
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] Registering platform 'homebridge-mqtt.mqtt'
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] ---
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] Loaded config.json with 0 accessories and 1 platforms.
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] ---
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] Loading 1 platforms...
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] [Config] Initializing config platform...
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] Loading 0 accessories...
May 15 18:42:52 LillePi homebridge[29463]: Load homebridge-mqtt.mqtt
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] [homebridge-mqtt.mqtt] config undefined or null!
May 15 18:42:52 LillePi homebridge[29463]: [2018-5-15 18:42:52] [homebridge-mqtt.mqtt] storagePath = /var/lib/homebridge-ext
May 15 18:42:52 LillePi systemd[1]: homebridge-ext.service: Main process exited, code=exited, status=1/FAILURE
May 15 18:42:52 LillePi systemd[1]: homebridge-ext.service: Unit entered failed state.
May 15 18:42:52 LillePi systemd[1]: homebridge-ext.service: Failed with result 'exit-code'.`

**Comment by oznu** [comment] 2018-05-16 10:02
Hi @bohtho,

This is what is causing the second instance to fail:

https://github.com/cflurin/homebridge-mqtt/blob/master/index.js#L34

The plugin should **not** exit the homebridge process just because it's not configured, it should just not do anything. The author could also just remove the `true` at the end of this line so it won't get loaded at all unless it exists in the `config.json`:

https://github.com/cflurin/homebridge-mqtt/blob/master/index.js#L24
