### ISSUE TITLE
Unable the view logfile

### ISSUE THREAD

**Issue by tomsteenbakkers** [oznu/homebridge-config-ui-x#21] opened 2018-01-28 14:12 UTC
First this: what a great plugin for die hard Homebridge users!

I have installed the Plugin and everything is working on one item: viewing the log. I have installed homebridge using the default settings (user homebridge and with systems). I have added the sudo option and added the option in `/etc/sudoers`

I can install plugin's, remove them but viewing the log file I get the following error:

```
Using systemd to tail logs
CMD: sudo -n journalctl -o cat -n 500 -f -u homebridge

chdir(2) failed.: Permission denied

The log tail command "sudo -n journalctl -o cat -n 500 -f -u homebridge" exited with code 1.
Please check the command in your config.json is correct.

See https://github.com/oznu/homebridge-config-ui-x#log-viewer-configuration for instructions.

```

Any idea what I'm doing wrong?

**Comment by oleg77s** [comment] 2018-01-28 17:58
The same for me:
[https://github.com/oznu/homebridge-config-ui-x/issues/17#issuecomment-360027118(url)

**Comment by oznu** [comment] 2018-01-28 23:33
I'll look more into this issue soon.

```
chdir(2) failed.: Permission denied
```

This might be caused by the CWD I'm setting when spawning the log command.

https://github.com/oznu/homebridge-config-ui-x/blob/master/src/wss/logs.ts#L113

**Comment by oznu** [comment] 2018-01-29 11:22
This should be fixed in 2.4.1.

**Closed** 2018-01-29 11:21 UTC

**Comment by oleg77s** [comment] 2018-01-29 16:12
yes, it works now
Thank you

**Comment by oznu** [comment] 2018-01-29 23:01
@oleg77s thanks for confirming it's working now 😄 .

Regarding those messages, they should only show up if "something" is attempting a connection. In the case of `jwt expired` that "something" is sending a valid token, but expired. Every minute is strange, the UI will not attempt to send a request using an expired token, and the WebSocket retry time is 3 seconds, not 60.

**Comment by oleg77s** [comment] 2018-01-30 05:27
its 3 sec now,
it was 60 sec yestarday 
strange :)

**Comment by muthomas** [comment] 2018-06-19 14:09
Unless I'm mistaken, that 'jwt expired' happens for me when I leave config-ui-x browser window open through a restart of homebridge.
