### ISSUE TITLE
V4.15.0 breaks menu

### ISSUE THREAD

**Issue by TimofeyK** [oznu/homebridge-config-ui-x#611] opened 2020-04-14 11:15 UTC
**Describe The Bug:**

After installing v4.15.0 the menu (hamburger) in mobile Safari does not react on taps

**To Reproduce:**

Install v4.15.0
Open UI in mobile Safari and tap on the menu button - nothing happens
Reverting to v4.14.0 restores the menu operations

**Expected behavior:**

Menu opens

**Environment:**

* **Node.js Version**:  v12.16.2
* **NPM Version**:  v6.14.4
* **Homebridge Version**:  0.4.54-beta.27
* **Homebridge Config UI X Version**:4.15.0
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment] 2020-04-14 11:23
Thanks for reporting this. This was caused by https://github.com/jquery/jquery/issues/4665. I'm reverting back to jQuery v3.4.1 for now.

**Comment by oznu** [comment] 2020-04-14 11:24
Fixed in v4.15.1.

**Closed** 2020-04-14 11:23 UTC
Labels: bug
