### ISSUE TITLE
Unable to recover HomeBridge Backup

### ISSUE THREAD

**Issue by dvbcheck** [oznu/homebridge-config-ui-x#1958] opened 2023-11-30 07:36 UTC
### Raspberry Pi Model

Raspberry Pi 4 B

### Describe The Bug

HomeBridge Image Bookworm 32 or 64 bit
<img width="372" alt="Bildschirmfoto 2023-11-26 um 11 35 06" src="https://github.com/homebridge/homebridge-raspbian-image/assets/64767341/f32f5598-95a6-4ae3-a217-fed505ce2855">

After flashing and starting the Pi I am not able to recover different HomeBridge backups. It ends after 1 second with error message: 

zlib: unexpected end of file.

**Comment by Cobra-James** [comment] 2023-12-01 13:55
I've got this issue also. Moving my Homebridge install from macOS native back to docker on another host, and receiving this error. I've moved this countless times without issue, first time I've seen this.

**Comment by NorthernMan54** [comment] 2023-12-01 14:00
@Cobra-James @dvbcheck  I would like to try and recreate this, so it can be resolved

Is it possible to DM me your backup file via the homebridge discord server ?

**Comment by NorthernMan54** [comment] 2023-12-01 14:01
Also from the command line on MacOS, you should be able to view the backup archive

```
tar tvzf homebridge-backup-BC223DE3CF31.tar.gz

drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/
-rw-r--r--  0 0      0        7314 29 Nov 08:30 plugins.json
-rw-r--r--  0 0      0          93 29 Nov 08:30 info.json
-rw-r--r--  0 0      0        1047 29 Nov 08:30 storage/.uix-dashboard.json
-rw-r--r--  0 0      0         131 29 Nov 08:30 storage/.uix-hb-service-homebridge-startup.json
-rw-r--r--  0 0      0          81 29 Nov 08:30 storage/.uix-secrets
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/accessories/
-rw-r--r--  0 0      0         351 29 Nov 08:30 storage/auth.json
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/backups/
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/bwp91_cache/
-rw-r--r--  0 0      0       17337 29 Nov 08:30 storage/config.json
-rw-r--r--  0 0      0       23775 29 Nov 08:30 storage/config.json.orig
-rw-r--r--  0 0      0         348 29 Nov 08:30 storage/config.json.release
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/homebridge-ewelink/
-rw-r--r--  0 0      0        1790 29 Nov 08:30 storage/homebridge-hue.json.gz
-rw-r--r--  0 0      0      121561 29 Nov 08:30 storage/jesse_130C86_ENERGY_Power_persist.json
-rw-r--r--  0 0      0      121173 29 Nov 08:30 storage/jesse_139827_ENERGY_Power_persist.json
-rw-r--r--  0 0      0      240226 29 Nov 08:30 storage/jesse_197602_AM2301_Temperature_persist.json
-rw-r--r--  0 0      0      249607 29 Nov 08:30 storage/jesse_860695_BME280_Temperature_persist.json
-rw-r--r--  0 0      0      121248 29 Nov 08:30 storage/jesse_F52066_ENERGY_Power_persist.json
-rw-r--r--  0 0      0      130797 29 Nov 08:30 storage/jesse_Wasaga_persist.json
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/persist/
-rw-r--r--  0 0      0       35362 29 Nov 08:30 storage/accessories/.cachedAccessories.0EBA1B4FCA8D.bak
-rw-r--r--  0 0      0        7882 29 Nov 08:30 storage/accessories/.cachedAccessories.0EF4E9FCADD1.bak
-rw-r--r--  0 0      0     1129927 29 Nov 08:30 storage/accessories/.cachedAccessories.1C223DE3CF34.bak
-rw-r--r--  0 0      0        8065 29 Nov 08:30 storage/accessories/.cachedAccessories.AC223DE3CF33.bak
-rw-r--r--  0 0      0       16111 29 Nov 08:30 storage/accessories/.cachedAccessories.BC223DE3CF33.bak
-rw-r--r--  0 0      0        6148 29 Nov 08:30 storage/accessories/.cachedAccessories.BC223DE3CF35.bak
-rw-r--r--  0 0      0       17114 29 Nov 08:30 storage/accessories/.cachedAccessories.CC223DE3CF30.bak
-rw-r--r--  0 0      0        5697 29 Nov 08:30 storage/accessories/.cachedAccessories.bak
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories
-rw-r--r--  0 0      0       35362 29 Nov 08:30 storage/accessories/cachedAccessories.0EBA1B4FCA8D
-rw-r--r--  0 0      0        7882 29 Nov 08:30 storage/accessories/cachedAccessories.0EF4E9FCADD1
-rw-r--r--  0 0      0      703364 29 Nov 08:30 storage/accessories/cachedAccessories.1C223DE3CF34
-rw-r--r--  0 0      0        8065 29 Nov 08:30 storage/accessories/cachedAccessories.AC223DE3CF33
-rw-r--r--  0 0      0       16557 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF32
-rw-r--r--  0 0      0       16111 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF33
-rw-r--r--  0 0      0        6148 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF35
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF40
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF41
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF42
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF43
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF44
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.BC223DE3CF45
-rw-r--r--  0 0      0       17114 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF30
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF32
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF33
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF36
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF37
-rw-r--r--  0 0      0           3 29 Nov 08:30 storage/accessories/cachedAccessories.CC223DE3CF38
-rw-r--r--  0 0      0       15537 29 Nov 08:30 storage/accessories/uiAccessoriesLayout.json
drwxr-xr-x  0 0      0           0 31 Dec  1969 storage/backups/config-backups/
-rw-r--r--  0 0      0         460 29 Nov 08:30 storage/persist/AccessoryInfo.0E5BA3A2C151.json
-rw-r--r--  0 0      0        1332 29 Nov 08:30 storage/persist/AccessoryInfo.0EBA1B4FCA8D.json
-rw-r--r--  0 0      0        1351 29 Nov 08:30 storage/persist/AccessoryInfo.0EF4E9FCADD1.json
-rw-r--r--  0 0      0        1333 29 Nov 08:30 storage/persist/AccessoryInfo.1C223DE3CF34.json
-rw-r--r--  0 0      0         457 29 Nov 08:30 storage/persist/AccessoryInfo.4A88A9995E0F.json
-rw-r--r--  0 0      0        1339 29 Nov 08:30 storage/persist/AccessoryInfo.595595A13F68.json
-rw-r--r--  0 0      0         455 29 Nov 08:30 storage/persist/AccessoryInfo.5E18B7B8E0C0.json
-rw-r--r--  0 0      0        1330 29 Nov 08:30 storage/persist/AccessoryInfo.7E947531A2DD.json
-rw-r--r--  0 0      0         456 29 Nov 08:30 storage/persist/AccessoryInfo.95981CE35321.json
-rw-r--r--  0 0      0        1334 29 Nov 08:30 storage/persist/AccessoryInfo.9B55105E2649.json
-rw-r--r--  0 0      0        1335 29 Nov 08:30 storage/persist/AccessoryInfo.AC223DE3CF33.json
-rw-r--r--  0 0      0        1329 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF31.json
-rw-r--r--  0 0      0        1483 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF32.json
-rw-r--r--  0 0      0        1334 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF33.json
-rw-r--r--  0 0      0        1350 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF35.json
-rw-r--r--  0 0      0        1330 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF40.json
-rw-r--r--  0 0      0        1336 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF41.json
-rw-r--r--  0 0      0        1330 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF42.json
-rw-r--r--  0 0      0        1335 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF43.json
-rw-r--r--  0 0      0        1331 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF44.json
-rw-r--r--  0 0      0        1337 29 Nov 08:30 storage/persist/AccessoryInfo.BC223DE3CF45.json
-rw-r--r--  0 0      0        1344 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF30.json
-rw-r--r--  0 0      0         463 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF32.json
-rw-r--r--  0 0      0        1328 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF33.json
-rw-r--r--  0 0      0         456 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF36.json
-rw-r--r--  0 0      0        1330 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF37.json
-rw-r--r--  0 0      0        1349 29 Nov 08:30 storage/persist/AccessoryInfo.CC223DE3CF38.json
-rw-r--r--  0 0      0         172 29 Nov 08:30 storage/persist/ControllerStorage.4A88A9995E0F.json
-rw-r--r--  0 0      0         172 29 Nov 08:30 storage/persist/ControllerStorage.595595A13F68.json
-rw-r--r--  0 0      0         172 29 Nov 08:30 storage/persist/ControllerStorage.657F969B5FC2.json
-rw-r--r--  0 0      0         172 29 Nov 08:30 storage/persist/ControllerStorage.7E947531A2DD.json
-rw-r--r--  0 0      0         172 29 Nov 08:30 storage/persist/ControllerStorage.9B55105E2649.json
-rw-r--r--  0 0      0         944 29 Nov 08:30 storage/persist/IdentifierCache.0E5BA3A2C151.json
-rw-r--r--  0 0      0       11637 29 Nov 08:30 storage/persist/IdentifierCache.0EBA1B4FCA8D.json
-rw-r--r--  0 0      0        2963 29 Nov 08:30 storage/persist/IdentifierCache.0EF4E9FCADD1.json
-rw-r--r--  0 0      0       40107 29 Nov 08:30 storage/persist/IdentifierCache.1C223DE3CF34.json
-rw-r--r--  0 0      0        3617 29 Nov 08:30 storage/persist/IdentifierCache.4A88A9995E0F.json
-rw-r--r--  0 0      0        3617 29 Nov 08:30 storage/persist/IdentifierCache.595595A13F68.json
-rw-r--r--  0 0      0        2953 29 Nov 08:30 storage/persist/IdentifierCache.5E18B7B8E0C0.json
-rw-r--r--  0 0      0        3617 29 Nov 08:30 storage/persist/IdentifierCache.7E947531A2DD.json
-rw-r--r--  0 0      0        3617 29 Nov 08:30 storage/persist/IdentifierCache.95981CE35321.json
-rw-r--r--  0 0      0        3617 29 Nov 08:30 storage/persist/IdentifierCache.9B55105E2649.json
-rw-r--r--  0 0      0        3560 29 Nov 08:30 storage/persist/IdentifierCache.AC223DE3CF33.json
-rw-r--r--  0 0      0        9975 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF31.json
-rw-r--r--  0 0      0       22076 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF32.json
-rw-r--r--  0 0      0        6163 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF33.json
-rw-r--r--  0 0      0        3181 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF35.json
-rw-r--r--  0 0      0        2590 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF40.json
-rw-r--r--  0 0      0        2715 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF41.json
-rw-r--r--  0 0      0        2047 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF42.json
-rw-r--r--  0 0      0        2047 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF43.json
-rw-r--r--  0 0      0        2163 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF44.json
-rw-r--r--  0 0      0        2715 29 Nov 08:30 storage/persist/IdentifierCache.BC223DE3CF45.json
-rw-r--r--  0 0      0        4575 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF30.json
-rw-r--r--  0 0      0        5881 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF32.json
-rw-r--r--  0 0      0       10481 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF33.json
-rw-r--r--  0 0      0       12125 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF36.json
-rw-r--r--  0 0      0        2047 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF37.json
-rw-r--r--  0 0      0       13429 29 Nov 08:30 storage/persist/IdentifierCache.CC223DE3CF38.json
-rw-r--r--  0 0      0      125168 29 Nov 08:30 storage/persist/jesse_Back Door_persist.json
-rw-r--r--  0 0      0      125168 29 Nov 08:30 storage/persist/jesse_DW2-Wi-Fi_persist.json
-rw-r--r--  0 0      0      125217 29 Nov 08:30 storage/persist/jesse_Patio Door_persist.json
-rw-r--r--  0 0      0      125217 29 Nov 08:30 storage/persist/jesse_Shed Door_persist.json
-rw-r--r--  0 0      0      125217 29 Nov 08:30 storage/persist/jesse_Shed Garage Door_persist.json
-rw-r--r--  0 0      0      125217 29 Nov 08:30 storage/persist/jesse_Side Door_persist.json
-rw-r--r--  0 0      0       17339 29 Nov 08:30 storage/backups/config-backups/config.json.1697459963960
```

**Comment by dvbcheck** [comment] 2023-12-01 19:11
> @Cobra-James @dvbcheck I would like to try and recreate this, so it can be resolved
> 
> Is it possible to DM me your backup file via the homebridge discord server ?

How can I transfer the backup to you? No account for discord.

**Comment by NorthernMan54** [comment] 2023-12-02 01:48
This should allow you to create an account

https://discord.com/invite/homebridge-432663330281226270

**Comment by NorthernMan54** [comment] 2023-12-30 15:36
Duplicate of #1856

**Closed as completed by NorthernMan54** 2023-12-30 15:36 UTC
Labels: bug
